### ISSUE TITLE
Joomla 3.4 - JHelperArray being passed non-array data

### ISSUE THREAD

**Issue by jh-github** [ITPrism/ITPMeta#9]
There are numberous instances of JHelperArray being passed non-array data in itpmetatags.php
Joomla 3.4 no longer accepts non-array data being passed and so throughs an error when variable type is not checked before passing.

**Comment by ITPrism** [comment]
Hi,
Thank you very much for the post!

I am going to fix it.
It will be done in next few days.

Best regards,
Todor

**Comment by ITPrism** [comment]
Fixed.
